### PR TITLE
add rtl support

### PR DESCRIPTION
**Pull request by dalirnet**
- vsAlert
- vsInput

### CODE REVIEW

**Comment by dalirnet** [comment]
- vsPagination

**Comment by dalirnet** [comment]
reset ```leftActive``` after change page count [17bcd98]

**Comment by dalirnet** [comment]
- vsSelect

**Comment by dalirnet** [comment]
- vsDialog

**Comment by luisDanielRoviraContreras** [comment]
@dalirnet plese resolve conflict

**Comment by dalirnet** [comment]
done

**Comment by NoahCardoza** [comment]
Is there a reason this hasn't been merged? I'm having the issue described in https://github.com/lusaxweb/vuesax-next/issues/23 and would love to see it fixed.

If there is a reason this isn't be merged I'd be happy to try and fix it, otherwise I'd have to fork the repo and merge it myself which isn't very beneficial to anyone else

**Comment by dalirnet** [comment]
I think @luisDanielRoviraContreras has abandoned the project 😅

**Comment by NoahCardoza** [comment]
I don't think so, https://github.com/lusaxweb/vuesax-next/commit/f1b48b2b3c456107f9b1c8fe8b0b34d6d6c9152b, that commit was made 3 hours ago. It's just the classic "this project doesn't feed me" scenario. I've experienced it myself with my own projects that I maintain.

I really hope he continues it since this is by far my favorite  UI component library right now. While it's buggy and lacking the number of components others have, I really love the look of it and think it has some great potential.

**Pull request closed without merging**
